### ISSUE TITLE
[Bug] Fix short background on mobile

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/portal#69]
**Describe the bug**
The Portal has some styling issues when page contents exceed the default height of a browser viewport.

**To Reproduce**
1. Sign into the Portal using a mobile viewport
2. Navigate to the Past Applications section
3. Have more than three applications in your account
4. See the dark background stop short and a white background appear below it

**Expected behavior**

**Screenshots**
![portal acmutd co_profile(Pixel 5) (1)](https://user-images.githubusercontent.com/16641570/150878827-dd2ad936-1c3c-4ed0-8f29-a6abd5ed21a2.png)

**Additional context**
This was reproduced on Chrome 97.0.4692.99 using the mobile emulator.

**Comment by Balstun** [comment]
**Suggestion:**
I suspect this issue is due to the `<CssBaseline />`  component, though I'm unable to replicate the bug on my local development environment. _Note that this bug is still visible on my mobile phone, with both the **Event Participation** and **Past Applications** sections_.

**Screenshots:**
![image](https://user-images.githubusercontent.com/42073460/150895958-04aa092f-3a81-48d3-ab83-0d23855d32bb.png)

**Next Actions:**
Test the portal with the previously used emulator, or specify the relevant settings to replicate the observed bug. Remove the `<CssBaseline />` to test if the issue is fixed. A similar issue was previously observed, for which the `<CssBaseline />` component was responsible
